name: Release LeviLaminaBDS[auto]

on:
  workflow_dispatch:
    inputs:
      LSE:
        description: 'LegacyScriptEngine include'
        required: false
        default: 'true'
      RUNTIME:
        description: 'Runtime for LeviLamina'
        required: false
        default: 'false'
      SCRIPTS:
        description: 'User scripts'
        required: false
        default: 'false'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Check Out
      uses: actions/checkout@v3
    - name: Get Latest Release
      id: latest_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: LiteLDev
        repo: LeviLamina
    - name: Remove 'v' from version
      id: format_version
      run: echo "::set-output name=version::${{ replace(steps.format_version.outputs.version , 'v', '') }}"
    - name: Check Out
      uses: actions/checkout@v3
    - name: Install Lip
      run: |
        rm README.md
        rm LICENSE
        Invoke-WebRequest -Uri https://github.com/lippkg/lip/releases/download/v0.21.2/lip-windows-amd64.zip -Outfile ./lip.zip
        unzip lip.zip
    - name: Install LeviLamina
      run: |
        mkdir llbds
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LeviLamina@${{ steps.format_version.outputs.version }}
        ls
    - name: Install LSE
      if: github.event.inputs.LSE == 'true'
      run: |
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LegacyScriptEngine
        cd ../
    - name: Install runtime
      if: github.event.inputs.RUNTIME == 'true'
      run: |
        cd llbds
        Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vc_redist.x64.exe -Outfile ./runtime_for_levilamina.exe
        cd ../
    - name: Run user scripts
      if: github.event.inputs.SCRIPTS == 'true'
      run: |
        cd llbds
        ../user_scripts.bat
        cd ../
    - name: Pack files
      run: |
        Invoke-WebRequest -Uri https://www.7-zip.org/a/7z2401-x64.exe -Outfile ./7z.exe
        .\7z.exe
        7z a -tzip llbds_${{ steps.format_version.outputs.version  }}.zip llbds\
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: llbds_${{ steps.format_version.outputs.version  }}.zip 
        name: LeviLaminaBDS - ${{ steps.format_version.outputs.version  }}
        tag_name: ${{ steps.format_version.outputs.version  }}
        body: |
          LeviLamina version: ${{ steps.format_version.outputs.version  }}
          Include LSE: ${{ github.event.inputs.LSE }}
          Include Runtime: ${{ github.event.inputs.RUNTIME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
