name: Pack LLBDS

on:
  workflow_dispatch:
    inputs:
      LL_VER:
        description: 'LeviLamina version'
        required: true
        default: '0.1.0'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    permissions:
      contents: write
    runs-on: windows-latest
    steps: 
    - name: Check Out
      uses: actions/checkout@v3
    - name: Prepare the environment
      run: |
        Invoke-RestMethod -Uri https://www.7-zip.org/a/7z2301-x64.msi
        7z2031-x64.msi
        rm README.md
        rm LICENSE
        Invoke-RestMethod -Uri https://github.com/lippkg/lip/releases/download/v0.21.2/lip-windows-amd64.zip
        unzip lip-windows-amd64.zip
    - name: Install & Pack LeviLamina
      run: |
        mkdir llbds
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LeviLamina@${{ github.event.inputs.LL_VER}}
        cd ../
        7z a -tzip llbds.zip llbds\
        ls
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: llbds.zip 
        name: LeviLaminaBDS - ${{ github.event.inputs.LL_VER }}
        tag_name: ${{ github.event.inputs.LL_VER }}
        body: |
          LeviLamina version: ${{ github.event.inputs.LL_VER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
