name: Pack LLBDS

on:
  workflow_dispatch:
    inputs:
      LL_VER:
        description: 'LeviLamina version'
        required: true
        default: '0.1.0'

jobs:
  build:
    runs-on: windows-latest
    steps: 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    - name: Prepare the environment
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
        scoop install main/zip 
        scoop install main/wget
        rm README.md
        rm LICENSE
        wget https://github.com/lippkg/lip/releases/download/v0.21.2/lip-windows-amd64.zip
        unzip lip-windows-amd64.zip
    - name: Install & Pack LeviLamina
      run: |
        mkdir llbds
        cd llbds
        ../lip.exe install -y github.com/LiteLDev/LeviLamina@${{ github.event.inputs.LL_VER}}
        cd ../
        7z a -tzip llbds.zip llbds\
        ls
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: llbds.zip 
        name: LeviLaminaBDS - ${{ github.event.inputs.LL_VER }}
        tag_name: ${{ github.event.inputs.LL_VER }}
        body: |
          LeviLamina version: ${{ github.event.inputs.LL_VER }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
